import HashMap
	from '../../../../src/algorithms/data-structures/hash-map/hash-map';

describe('Hash Map', function() {
	const keyValuePairs = [
		{key: 'apple', value: 'fruit'},
		{key: 'dog', value: 'animal'},
		{key: 'sun', value: 'star'},
		{key: 'moon', value: 'satellite'},
		{key: 'car', value: 'vehicle'},
		{key: 'tree', value: 'plant'},
		{key: 'river', value: 'water'},
		{key: 'mountain', value: 'landform'},
		{key: 'cup', value: 'container'},
		{key: 'book', value: 'reading'},
		{key: 'phone', value: 'communication'},
		{key: 'ocean', value: 'sea'},
		{key: 'sand', value: 'beach'},
		{key: 'cloud', value: 'sky'},
		{key: 'music', value: 'melody'},
		{key: 'pencil', value: 'writing'},
		{key: 'shoe', value: 'footwear'},
		{key: 'house', value: 'home'},
		{key: 'guitar', value: 'instrument'},
		{key: 'bread', value: 'food'},
		{key: 'butterfly', value: 'insect'},
		{key: 'chocolate', value: 'candy'},
		{key: 'elephant', value: 'mammal'},
		{key: 'kangaroo', value: 'marsupial'},
		{key: 'whale', value: 'mammal'},
		{key: 'dolphin', value: 'mammal'},
		{key: 'zebra', value: 'animal'},
		{key: 'lion', value: 'animal'},
		{key: 'tiger', value: 'cat'},
		{key: 'rabbit', value: 'animal'},
		{key: 'snail', value: 'mollusk'},
		{key: 'ant', value: 'insect'},
		{key: 'spider', value: 'arachnid'},
		{key: 'bird', value: 'avian'},
		{key: 'fish', value: 'aquatic'},
		{key: 'frog', value: 'amphibian'},
		{key: 'lizard', value: 'reptile'},
		{key: 'turtle', value: 'reptile'},
		{key: 'horse', value: 'animal'},
		{key: 'monkey', value: 'primate'},
		{key: 'almond', value: 'nut'},
		{key: 'rose', value: 'flower'},
		{key: 'daisy', value: 'flower'},
		{key: 'oak', value: 'tree'},
		{key: 'pine', value: 'tree'},
		{key: 'maple', value: 'tree'},
		{key: 'paper', value: 'material'},
		{key: 'glass', value: 'material'},
		{key: 'metal', value: 'material'},
		{key: 'silver', value: 'element'},
		{key: 'gold', value: 'element'},
		{key: 'copper', value: 'element'},
		{key: 'iron', value: 'element'},
		{key: 'mercury', value: 'element'},
		{key: 'lead', value: 'element'},
		{key: 'platinum', value: 'element'},
		{key: 'rice', value: 'grain'},
		{key: 'wheat', value: 'grain'},
		{key: 'corn', value: 'grain'},
		{key: 'oat', value: 'grain'},
		{key: 'barley', value: 'grain'},
		{key: 'sofa', value: 'furniture'},
		{key: 'chair', value: 'furniture'},
		{key: 'table', value: 'furniture'},
		{key: 'desk', value: 'furniture'},
		{key: 'bed', value: 'furniture'},
		{key: 'dresser', value: 'furniture'},
		{key: 'mirror', value: 'object'},
		{key: 'lamp', value: 'light'},
		{key: 'bulb', value: 'light'},
		{key: 'battery', value: 'energy'},
		{key: 'electricity', value: 'energy'},
		{key: 'gas', value: 'fuel'},
		{key: 'petrol', value: 'fuel'},
		{key: 'diesel', value: 'fuel'},
		{key: 'coat', value: 'clothing'},
		{key: 'pants', value: 'clothing'},
		{key: 'shirt', value: 'clothing'},
		{key: 'shoe', value: 'clothing'},
		{key: 'hat', value: 'clothing'},
		{key: 'glove', value: 'clothing'},
		{key: 'scarf', value: 'clothing'},
		{key: 'umbrella', value: 'protection'},
		{key: 'sunscreen', value: 'protection'},
		{key: 'raincoat', value: 'protection'},
		{key: 'watch', value: 'timepiece'},
		{key: 'clock', value: 'timepiece'},
		{key: 'timer', value: 'timepiece'},
		{key: 'alarm', value: 'alert'},
		{key: 'bell', value: 'sound'},
		{key: 'whistle', value: 'sound'},
		{key: 'horn', value: 'sound'},
		{key: 'drum', value: 'instrument'},
		{key: 'flute', value: 'instrument'},
		{key: 'piano', value: 'instrument'},
	];


	it('should test hash map', function() {
		const hashMap: HashMap = new HashMap();
		keyValuePairs.forEach(({key, value}) => hashMap.put(key, value));
		console.log(hashMap.getData());
	});
});
